/// <summary>
/// スキルのEnum
/// </summary>
public enum SkillEnum
{
    ControlCollapse,
    PersonalityReplacement,
    ConsciousnessDissociation,
    ImitationBehavior,
    SelfCorrosion,
    InternalCollapse,
    SurfaceErosion,
    ParasiteMarkManifestation,
    PublicAttraction,
    BiologicalEnhancement,
    Activation,
    SelfDestructionBehavior,
    DreamDeepening,
    DestructionImpulse,
    Seizure,
    Madness,
    EmotionalCollapse,
    Phantasm,
    CognitiveConfusion,
    Intoxication,
    SensorySedation,
    Euphoria,
    DeathPerformance,
    BloodCamouflage,
    WoundCamouflage,
    PhysicalTransformation,
    MentalErosion,
    Parasite,
    WaterborneInfection,
    FoodborneInfection,
    ZoonoticInfection,
    Bloodsucker_MediatedInfection,
    SurfaceParasiticInfection,
    AerosolizedInfection,
    DirectContactInfection,
    DropletInfection,
    MucosalInfection,
    BloodborneInfectionIII,
    BloodborneInfectionII,
    BloodborneInfectionI,
}
